intraway_avatar_homepage:
    path:     /
    defaults: { _controller: IntrawayAvatarBundle:Default:index}

intraway_avatar_upload:
    path:     /avatars/
    defaults: { _controller: IntrawayAvatarBundle:ApiRest:upload}
    methods:  [POST]

intraway_avatar_api:
    path:     /avatars/{id}
    defaults: { _controller: IntrawayAvatarBundle:ApiRest:index, id: 9999}
    requirements:
        id : \d+
    methods:  [GET]
