Intraway\AvatarBundle\Entity\Avatars:
    type: entity
    table: avatars
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
        mimetype:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        size:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
